#!/bin/bash

cwd=$(pwd)
echo ${cwd}

source venv/bin/activate
pip install -r requirements.txt

# Generate static files.
cd qadmin/frontend
npm install && npm build

# Start server
cd ${cwd}/qadmin
python manage.py runserver 10.0.0.10:8000
