#!/bin/bash

cwd=$(pwd)

python3.6 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

cd ${cwd}/qadmin
python manage.py migrate

# Generate static files.
cd ${cwd}/qadmin/frontend
npm install && npm run build
