# Generated by Django 3.0.3 on 2020-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('categories', models.CharField(choices=[(11, 'Algorithm'), (12, 'Data Structure'), (13, 'Trick'), (11, 'Programming'), (12, 'Games'), (21, 'Operatiing System'), (32, 'Control Theory')], default=11, max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('solution', models.CharField(max_length=1000)),
            ],
        ),
    ]
