# Generated by Django 3.0.3 on 2020-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.CharField(choices=[(11, 'Algorithm'), (12, 'Data Structure'), (13, 'Trick'), (14, 'Programming'), (15, 'Games'), (21, 'Operatiing System'), (32, 'Control Theory')], default=11, max_length=20),
        ),
    ]
