# Generated by Django 3.0.3 on 2020-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='engineer@pony.ai', max_length=100),
        ),
    ]
