# Generated by Django 3.0.3 on 2020-02-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200205_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.CharField(max_length=100),
        ),
    ]
