# Generated by Django 3.0.3 on 2020-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='references',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='supplement',
            field=models.TextField(default=''),
        ),
    ]
